# Generated by Django 4.2 on 2024-03-06 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='is_active')),
                ('is_download', models.BooleanField(default=False, verbose_name='is_download')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='updated_date')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('link', models.URLField(default='example.com', verbose_name='link')),
                ('posted', models.DateTimeField(blank=True, null=True, verbose_name='Costume DateTime')),
            ],
            options={
                'ordering': ('pk',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='is_active')),
                ('is_download', models.BooleanField(default=False, verbose_name='is_download')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='updated_date')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('link', models.URLField(default='example.com', verbose_name='link')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='is_active')),
                ('is_download', models.BooleanField(default=False, verbose_name='is_download')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='updated_date')),
                ('title', models.CharField(max_length=100, verbose_name='category')),
                ('link', models.URLField(default='example.com', verbose_name='link')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='is_active')),
                ('is_download', models.BooleanField(default=False, verbose_name='is_download')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='updated_date')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
            ],
            options={
                'verbose_name': 'Key Word',
                'verbose_name_plural': 'Key Words',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='KeyWordResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='is_active')),
                ('is_download', models.BooleanField(default=False, verbose_name='is_download')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='updated_date')),
                ('keyword', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.keyword', verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Key Word Result',
                'verbose_name_plural': 'Key Word Results',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='is_active')),
                ('is_download', models.BooleanField(default=False, verbose_name='is_download')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='updated_date')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('link', models.URLField(default='example.com', verbose_name='link')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='KeyWordResultItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='is_active')),
                ('is_download', models.BooleanField(default=False, verbose_name='is_download')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='updated_date')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.article', verbose_name='Category')),
                ('keyword_result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.keywordresult', verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Key Word Result Item',
                'verbose_name_plural': 'Key Word Result Items',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='is_active')),
                ('is_download', models.BooleanField(default=False, verbose_name='is_download')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='updated_date')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.article', verbose_name='Author')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.tag', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Article Tag',
                'verbose_name_plural': 'Article Tags',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.author', verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.category', verbose_name='Category'),
        ),
    ]
