# Generated by Django 4.2 on 2024-03-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='posted',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Posted at '),
        ),
    ]
