# Generated by Django 4.2 on 2024-03-07 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletag',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.article', verbose_name='Article'),
        ),
        migrations.AlterField(
            model_name='articletag',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.tag', verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='keywordresult',
            name='keyword',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.keyword', verbose_name='Key Word'),
        ),
        migrations.AlterField(
            model_name='keywordresultitem',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.article', verbose_name='Article'),
        ),
        migrations.AlterField(
            model_name='keywordresultitem',
            name='keyword_result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.keywordresult', verbose_name='Key Word'),
        ),
    ]
